module.exports = require('optimist')
  .alias('u', 'url')
  .describe('u', 'Base application URL')
  .default('u', 'http://localhost:3000')
  .alias('p', 'port')
  .describe('p', 'Port number for the Express application')
  .default('p', 3000)
  .describe('redis-host', 'Redis Server hostname')
  .default('redis-host', process.env.REDIS_HOST || localhost)
  .describe('redis-port', 'Redis Server port number')
  .default('redis-port', 6379)
  .describe('redis-pass', 'Redis Server password')
  .default('redis-pass', false)
  .argv;
